### ISSUE TITLE
Styling for Profile userData not upto mark

### ISSUE THREAD

**Issue by sugandhakhera** [Apoorva2405/image-viewer#24]

**Comment by Apoorva2405** [comment]
Can we add some description or screenshot in these issues?

**Comment by Apoorva2405** [comment]
1) Profile picture icon should be large
2) Edit icon should appear alongside profile name
3)Spacing between name and posts count

**Comment by Apoorva2405** [comment]
4) Also, entire profile needs to be in center

**Comment by Apoorva2405** [comment]
Fixed
